services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: .
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - backend

volumes:
  mysql_data: 