services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=nexusboards.online
      - DB_USER=nexus_board_usr
      - DB_PASSWORD=123qWe098
      - DB_NAME=nexus_boards
      - DB_PORT=3306

  frontend:
    build: .
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - backend
volumes:
  mysql_data: 